#!/usr/bin/env python3
"""Build deterministic, reviewable Central pedestrian topology from OSM.

This host-Python tool deliberately stops before Cesium collision admission.
OpenStreetMap supplies pedestrian intent and XY topology; the companion Unreal
projection/certification scripts supply project coordinates and physical truth.

The default 450 m by 300 m core is centered on the centroid of the validated
30-source signal study.  It is divided into six stable 3-by-2 cells.  All
defaults are command-line overridable and every accepted/rejected rule is
reported in the audit mirror.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import re
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import uuid
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence


GENERATOR_NAME = "TelecomTwin Central OSM pipeline"
GENERATOR_VERSION = "1.0.0"
SCHEMA_VERSION = 1
DATASET_ID = "hk-central-signal-core-v1"
DEFAULT_OVERPASS_URL = "https://overpass-api.de/api/interpreter"
USER_AGENT = (
    "TelecomTwin-Central-Network-Importer/1.0 "
    "(UE digital-twin demo; https://www.openstreetmap.org/copyright)"
)

# Approx. 450 m east/west by 300 m north/south at 22.28 N.  The center is the
# WGS84 estimate of the validated signal-source centroid, not an arbitrary map
# point.  Exact project XY is generated by CesiumGeoreference in Unreal.
DEFAULT_BBOX_TEXT = "22.27849,114.16364,22.28120,114.16800"
GRID_COLUMNS = 3
GRID_ROWS = 2

SCRIPT_DIR = Path(__file__).resolve().parent
SCHEMA_PATH = SCRIPT_DIR / "central_pedestrian_source.schema.json"
PROJECTED_SCHEMA_PATH = SCRIPT_DIR / "central_pedestrian_unreal_source.schema.json"
DEFAULT_CORRECTIONS_PATH = SCRIPT_DIR / "central_manual_corrections.json"
DEFAULT_FIXTURE_PATH = SCRIPT_DIR / "fixtures" / "central_osm_minimal.json"
DEFAULT_OUTPUT_PATH = SCRIPT_DIR / "Data" / "central_pedestrian_source.json"
DEFAULT_RAW_OUTPUT_PATH = SCRIPT_DIR / "Data" / "central_osm_overpass_raw.json"
DEFAULT_AUDIT_OUTPUT_PATH = (
    SCRIPT_DIR / "Data" / "central_pedestrian_source.audit.json"
)

ALLOWED_HIGHWAYS = frozenset(
    {"footway", "pedestrian", "path", "steps", "service", "residential"}
)
DENIED_ACCESS = frozenset({"no", "private", "customers"})
FOOT_POSITIVE = frozenset({"yes", "designated", "permissive"})
VEHICLE_RESTRICTED = frozenset({"no", "private"})
SIDEWALK_POSITIVE = frozenset({"yes", "both", "left", "right"})
SIDEWALK_NEGATIVE = frozenset({"no", "none", "separate"})
STABLE_ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
COORDINATE_DIGITS = 8
HASH_PLACEHOLDER = "0" * 64
BUILD_NAMESPACE = uuid.UUID("80acafee-cbc5-52e8-b1c6-b385ec540d64")


class PipelineError(RuntimeError):
    """Expected, user-actionable pipeline failure."""


@dataclass(frozen=True)
class BBox:
    south: float
    west: float
    north: float
    east: float

    @classmethod
    def parse(cls, value: str) -> "BBox":
        try:
            south, west, north, east = (float(part) for part in value.split(","))
        except (TypeError, ValueError) as error:
            raise PipelineError(
                "bbox must be south,west,north,east in WGS84 degrees"
            ) from error
        bbox = cls(south=south, west=west, north=north, east=east)
        bbox.validate()
        return bbox

    def validate(self) -> None:
        if not (-90.0 <= self.south < self.north <= 90.0):
            raise PipelineError("bbox requires -90 <= south < north <= 90")
        if not (-180.0 <= self.west < self.east <= 180.0):
            raise PipelineError("bbox requires -180 <= west < east <= 180")

    def as_dict(self) -> dict[str, float]:
        return {
            "south": round(self.south, COORDINATE_DIGITS),
            "west": round(self.west, COORDINATE_DIGITS),
            "north": round(self.north, COORDINATE_DIGITS),
            "east": round(self.east, COORDINATE_DIGITS),
        }

    def contains(self, longitude: float, latitude: float, epsilon: float = 1e-11) -> bool:
        return (
            self.west - epsilon <= longitude <= self.east + epsilon
            and self.south - epsilon <= latitude <= self.north + epsilon
        )

    @property
    def longitude_step(self) -> float:
        return (self.east - self.west) / GRID_COLUMNS

    @property
    def latitude_step(self) -> float:
        return (self.north - self.south) / GRID_ROWS

    def cell_bounds(self, column: int, row: int) -> "BBox":
        west = self.west + column * self.longitude_step
        east = self.west + (column + 1) * self.longitude_step
        south = self.south + row * self.latitude_step
        north = self.south + (row + 1) * self.latitude_step
        return BBox(south=south, west=west, north=north, east=east)

    def cell_for(self, longitude: float, latitude: float) -> tuple[int, int]:
        if not self.contains(longitude, latitude):
            raise PipelineError(
                f"coordinate ({longitude}, {latitude}) lies outside configured bbox"
            )
        column = min(
            GRID_COLUMNS - 1,
            max(0, int(math.floor((longitude - self.west) / self.longitude_step))),
        )
        row = min(
            GRID_ROWS - 1,
            max(0, int(math.floor((latitude - self.south) / self.latitude_step))),
        )
        return column, row

    @property
    def vertical_boundaries(self) -> tuple[float, ...]:
        return tuple(
            self.west + index * self.longitude_step
            for index in range(GRID_COLUMNS + 1)
        )

    @property
    def horizontal_boundaries(self) -> tuple[float, ...]:
        return tuple(
            self.south + index * self.latitude_step
            for index in range(GRID_ROWS + 1)
        )


@dataclass(frozen=True)
class SourcePoint:
    point_id: str
    longitude: float
    latitude: float
    osm_node_id: int | None
    is_cell_boundary: bool = False

    def as_dict(self) -> dict[str, Any]:
        return {
            "point_id": self.point_id,
            "longitude": round(self.longitude, COORDINATE_DIGITS),
            "latitude": round(self.latitude, COORDINATE_DIGITS),
            "osm_node_id": self.osm_node_id,
            "is_cell_boundary": self.is_cell_boundary,
        }


@dataclass(frozen=True)
class Admission:
    accepted: bool
    classification: str | None
    rule: str
    requires_manual_review: bool = False


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def sha256_value(value: Any) -> str:
    return hashlib.sha256(canonical_json_bytes(value)).hexdigest()


def write_pretty_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        indent=2,
        allow_nan=False,
    )
    path.write_text(text + "\n", encoding="utf-8")


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise PipelineError(f"JSON file does not exist: {path}") from error
    except json.JSONDecodeError as error:
        raise PipelineError(f"invalid JSON in {path}: {error}") from error


def cell_id(column: int, row: int) -> str:
    return f"central-r{row}-c{column}"


def normalise_tags(tags: Any) -> dict[str, str]:
    if not isinstance(tags, dict):
        return {}
    return {
        str(key): str(value)
        for key, value in sorted(tags.items(), key=lambda item: str(item[0]))
    }


def has_positive_sidewalk(tags: dict[str, str]) -> bool:
    values = [
        tags[key].lower()
        for key in ("sidewalk", "sidewalk:left", "sidewalk:right", "sidewalk:both")
        if key in tags
    ]
    if not values:
        return False
    return any(value in SIDEWALK_POSITIVE for value in values) and not all(
        value in SIDEWALK_NEGATIVE for value in values
    )


def classify_way(tags: dict[str, str]) -> Admission:
    """Apply the explicit pedestrian allow-list; unknown semantics fail closed."""

    highway = tags.get("highway", "").lower()
    if highway not in ALLOWED_HIGHWAYS:
        return Admission(False, None, "reject-highway-not-allowed")
    if tags.get("area", "").lower() == "yes":
        return Admission(False, None, "reject-area-polygon")
    if tags.get("indoor", "").lower() == "yes":
        return Admission(False, None, "reject-indoor")
    if tags.get("access", "").lower() in DENIED_ACCESS:
        return Admission(False, None, "reject-access-denied")
    if tags.get("foot", "").lower() in DENIED_ACCESS:
        return Admission(False, None, "reject-foot-denied")
    if any(
        key in tags
        for key in ("construction", "proposed", "abandoned", "disused")
    ):
        return Admission(False, None, "reject-lifecycle")

    if highway == "pedestrian":
        return Admission(True, "pedestrian-zone", "allow-highway-pedestrian")
    if highway == "steps":
        return Admission(True, "footway", "allow-highway-steps")
    if highway == "path":
        return Admission(True, "footway", "allow-highway-path")
    if highway == "footway":
        is_crossing = (
            tags.get("footway", "").lower() == "crossing"
            or "crossing" in tags
            or any(key.startswith("crossing:") for key in tags)
        )
        if is_crossing:
            return Admission(True, "crossing", "allow-footway-crossing")
        if tags.get("footway", "").lower() == "sidewalk":
            return Admission(True, "sidewalk", "allow-footway-sidewalk")
        return Admission(True, "footway", "allow-highway-footway")

    # service/residential centerlines are never silently treated as sidewalks.
    # They enter the review overlay only when OSM contains explicit pedestrian
    # evidence, and remain marked requires_manual_review until a correction or
    # later certification workflow promotes the intended side of the street.
    if has_positive_sidewalk(tags):
        return Admission(
            True,
            "sidewalk",
            "allow-road-explicit-sidewalk-review",
            requires_manual_review=True,
        )

    foot = tags.get("foot", "").lower()
    vehicle = tags.get("vehicle", "").lower()
    motor_vehicle = tags.get("motor_vehicle", "").lower()
    pedestrian = tags.get("pedestrian", "").lower()
    if (
        pedestrian in FOOT_POSITIVE
        or (
            foot in FOOT_POSITIVE
            and (vehicle in VEHICLE_RESTRICTED or motor_vehicle in VEHICLE_RESTRICTED)
        )
    ):
        return Admission(
            True,
            "footway",
            "allow-road-explicit-foot-review",
            requires_manual_review=True,
        )

    return Admission(False, None, "reject-road-without-pedestrian-evidence")


def directionality(tags: dict[str, str]) -> str:
    oneway_foot = tags.get("oneway:foot", "").lower()
    if oneway_foot in {"yes", "true", "1"}:
        return "forward"
    if oneway_foot in {"-1", "reverse"}:
        return "reverse"
    if (
        tags.get("foot:forward", "").lower() == "no"
        and tags.get("foot:backward", "").lower() != "no"
    ):
        return "reverse"
    if (
        tags.get("foot:backward", "").lower() == "no"
        and tags.get("foot:forward", "").lower() != "no"
    ):
        return "forward"
    return "bidirectional"


def make_overpass_query(bbox: BBox) -> str:
    values = "|".join(sorted(ALLOWED_HIGHWAYS))
    bounds = f"{bbox.south:.8f},{bbox.west:.8f},{bbox.north:.8f},{bbox.east:.8f}"
    return (
        "[out:json][timeout:90];\n"
        "(\n"
        f'  way["highway"~"^({values})$"]({bounds});\n'
        ");\n"
        "out body;\n"
        ">;\n"
        "out skel qt;\n"
    )


def fetch_overpass(url: str, query: str, timeout_seconds: float) -> dict[str, Any]:
    body = urllib.parse.urlencode({"data": query}).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=body,
        headers={"User-Agent": USER_AGENT, "Accept": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
            payload = response.read()
    except (OSError, urllib.error.URLError, urllib.error.HTTPError) as error:
        raise PipelineError(f"Overpass request failed: {error}") from error
    try:
        document = json.loads(payload.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise PipelineError("Overpass returned non-JSON content") from error
    if not isinstance(document, dict) or not isinstance(document.get("elements"), list):
        raise PipelineError("Overpass response does not contain an elements array")
    return document


def normalise_overpass_document(document: dict[str, Any]) -> dict[str, Any]:
    result = copy.deepcopy(document)
    elements = result.get("elements")
    if not isinstance(elements, list):
        raise PipelineError("OSM input requires an elements array")
    type_order = {"node": 0, "way": 1, "relation": 2}
    result["elements"] = sorted(
        elements,
        key=lambda element: (
            type_order.get(str(element.get("type")), 99),
            int(element.get("id", 0)),
        ),
    )
    return result


def _coordinate_equal(a: SourcePoint, b: SourcePoint, epsilon: float = 1e-10) -> bool:
    return (
        abs(a.longitude - b.longitude) <= epsilon
        and abs(a.latitude - b.latitude) <= epsilon
    )


def _on_grid_boundary(bbox: BBox, longitude: float, latitude: float) -> bool:
    epsilon = 1e-10
    return any(
        abs(longitude - boundary) <= epsilon for boundary in bbox.vertical_boundaries
    ) or any(
        abs(latitude - boundary) <= epsilon for boundary in bbox.horizontal_boundaries
    )


def _interpolate_point(
    start: SourcePoint,
    end: SourcePoint,
    fraction: float,
    bbox: BBox,
    parent_feature_id: str,
) -> SourcePoint:
    if fraction <= 1e-12:
        return SourcePoint(
            start.point_id,
            start.longitude,
            start.latitude,
            start.osm_node_id,
            _on_grid_boundary(bbox, start.longitude, start.latitude),
        )
    if fraction >= 1.0 - 1e-12:
        return SourcePoint(
            end.point_id,
            end.longitude,
            end.latitude,
            end.osm_node_id,
            _on_grid_boundary(bbox, end.longitude, end.latitude),
        )
    longitude = start.longitude + (end.longitude - start.longitude) * fraction
    latitude = start.latitude + (end.latitude - start.latitude) * fraction
    coordinate_key = f"{longitude:.{COORDINATE_DIGITS}f},{latitude:.{COORDINATE_DIGITS}f}"
    suffix = hashlib.sha256(coordinate_key.encode("ascii")).hexdigest()[:12]
    return SourcePoint(
        point_id=f"{parent_feature_id}-split-{suffix}",
        longitude=longitude,
        latitude=latitude,
        osm_node_id=None,
        is_cell_boundary=True,
    )


def _segment_fractions(start: SourcePoint, end: SourcePoint, bbox: BBox) -> list[float]:
    fractions = {0.0, 1.0}
    delta_longitude = end.longitude - start.longitude
    delta_latitude = end.latitude - start.latitude
    if abs(delta_longitude) > 1e-15:
        for boundary in bbox.vertical_boundaries:
            fraction = (boundary - start.longitude) / delta_longitude
            if 1e-12 < fraction < 1.0 - 1e-12:
                fractions.add(fraction)
    if abs(delta_latitude) > 1e-15:
        for boundary in bbox.horizontal_boundaries:
            fraction = (boundary - start.latitude) / delta_latitude
            if 1e-12 < fraction < 1.0 - 1e-12:
                fractions.add(fraction)
    return sorted(fractions)


def split_polyline_into_cells(
    points: Sequence[SourcePoint], bbox: BBox, parent_feature_id: str
) -> list[tuple[str, list[SourcePoint]]]:
    """Clip a polyline to the core and split it at every stable cell boundary."""

    runs: list[tuple[str, list[SourcePoint]]] = []
    current_cell: str | None = None
    current_points: list[SourcePoint] = []

    def finish_run() -> None:
        nonlocal current_cell, current_points
        if current_cell is not None and len(current_points) >= 2:
            if any(
                not _coordinate_equal(current_points[index - 1], current_points[index])
                for index in range(1, len(current_points))
            ):
                runs.append((current_cell, current_points))
        current_cell = None
        current_points = []

    for start, end in zip(points, points[1:]):
        if _coordinate_equal(start, end):
            continue
        fractions = _segment_fractions(start, end, bbox)
        for fraction_start, fraction_end in zip(fractions, fractions[1:]):
            middle_fraction = (fraction_start + fraction_end) * 0.5
            middle_longitude = start.longitude + (
                end.longitude - start.longitude
            ) * middle_fraction
            middle_latitude = start.latitude + (
                end.latitude - start.latitude
            ) * middle_fraction
            if not bbox.contains(middle_longitude, middle_latitude):
                finish_run()
                continue
            column, row = bbox.cell_for(middle_longitude, middle_latitude)
            segment_cell = cell_id(column, row)
            segment_start = _interpolate_point(
                start, end, fraction_start, bbox, parent_feature_id
            )
            segment_end = _interpolate_point(
                start, end, fraction_end, bbox, parent_feature_id
            )
            if current_cell != segment_cell:
                finish_run()
                current_cell = segment_cell
                current_points = [segment_start, segment_end]
            else:
                if not _coordinate_equal(current_points[-1], segment_start):
                    finish_run()
                    current_cell = segment_cell
                    current_points = [segment_start, segment_end]
                elif not _coordinate_equal(current_points[-1], segment_end):
                    current_points.append(segment_end)
        # A segment end outside the outer bbox must not join to a later segment.
        if not bbox.contains(end.longitude, end.latitude):
            finish_run()
    finish_run()
    return runs


def validate_manual_corrections(document: Any, dataset_id: str) -> list[dict[str, Any]]:
    if not isinstance(document, dict):
        raise PipelineError("manual corrections root must be an object")
    if document.get("schema_version") != SCHEMA_VERSION:
        raise PipelineError("manual corrections schema_version must be 1")
    if document.get("dataset_id") != dataset_id:
        raise PipelineError(
            "manual corrections dataset_id must match the topology dataset_id"
        )
    corrections = document.get("corrections")
    if not isinstance(corrections, list):
        raise PipelineError("manual corrections must contain a corrections array")
    seen: set[str] = set()
    normalised: list[dict[str, Any]] = []
    for index, raw in enumerate(corrections):
        if not isinstance(raw, dict):
            raise PipelineError(f"correction {index} must be an object")
        correction = copy.deepcopy(raw)
        correction_id = correction.get("correction_id")
        if not isinstance(correction_id, str) or not STABLE_ID_RE.fullmatch(correction_id):
            raise PipelineError(f"correction {index} has an invalid correction_id")
        if correction_id in seen:
            raise PipelineError(f"duplicate correction_id: {correction_id}")
        seen.add(correction_id)
        operation = correction.get("operation")
        if operation not in {"add", "exclude", "reclassify"}:
            raise PipelineError(f"{correction_id}: unsupported operation {operation!r}")
        if correction.get("review_status") not in {"pending", "accepted", "rejected"}:
            raise PipelineError(f"{correction_id}: invalid review_status")
        if not isinstance(correction.get("reason"), str) or not correction["reason"].strip():
            raise PipelineError(f"{correction_id}: reason is required")
        target = correction.get("target_parent_feature_id")
        if operation in {"exclude", "reclassify"} and (
            not isinstance(target, str) or not STABLE_ID_RE.fullmatch(target)
        ):
            raise PipelineError(f"{correction_id}: valid target_parent_feature_id required")
        classification = correction.get("classification")
        allowed_classes = {
            "sidewalk",
            "footway",
            "crossing",
            "pedestrian-zone",
            "manual-pedestrian-link",
        }
        if operation in {"add", "reclassify"} and classification not in allowed_classes:
            raise PipelineError(f"{correction_id}: valid classification required")
        if operation == "add":
            geometry = correction.get("points_wgs84")
            if not isinstance(geometry, list) or len(geometry) < 2:
                raise PipelineError(f"{correction_id}: add requires two or more points")
            for point in geometry:
                if (
                    not isinstance(point, list)
                    or len(point) != 2
                    or not all(isinstance(value, (int, float)) for value in point)
                ):
                    raise PipelineError(f"{correction_id}: invalid WGS84 point")
        normalised.append(correction)
    return sorted(normalised, key=lambda correction: correction["correction_id"])


def _feature_from_run(
    *,
    parent_feature_id: str,
    origin: dict[str, Any],
    classification: str,
    admission_rule: str,
    requires_manual_review: bool,
    feature_cell_id: str,
    part_index: int,
    way_directionality: str,
    points: Sequence[SourcePoint],
    tags: dict[str, str],
) -> dict[str, Any]:
    feature_id = (
        f"{parent_feature_id}-{feature_cell_id}-part-{part_index:03d}"
    )
    point_documents = [point.as_dict() for point in points]
    return {
        "feature_id": feature_id,
        "parent_feature_id": parent_feature_id,
        "origin": origin,
        "classification": classification,
        "admission_rule": admission_rule,
        "requires_manual_review": requires_manual_review,
        "cell_id": feature_cell_id,
        "part_index": part_index,
        "directionality": way_directionality,
        "points": point_documents,
        "tags": tags,
        "geometry_sha256": sha256_value(point_documents),
    }


def geodesic_length_m(points: Sequence[dict[str, Any]]) -> float:
    """Return WGS84 polyline length with a stable spherical approximation."""

    earth_radius_m = 6371008.8
    length_m = 0.0
    for start, end in zip(points, points[1:]):
        latitude_a = math.radians(float(start["latitude"]))
        latitude_b = math.radians(float(end["latitude"]))
        delta_latitude = latitude_b - latitude_a
        delta_longitude = math.radians(
            float(end["longitude"]) - float(start["longitude"])
        )
        haversine = (
            math.sin(delta_latitude * 0.5) ** 2
            + math.cos(latitude_a)
            * math.cos(latitude_b)
            * math.sin(delta_longitude * 0.5) ** 2
        )
        length_m += 2.0 * earth_radius_m * math.asin(min(1.0, math.sqrt(haversine)))
    return length_m


def coarse_connected_component_count(features: Sequence[dict[str, Any]]) -> int:
    """Count XY topology components using stable shared OSM/split point ids."""

    adjacency: dict[str, set[str]] = {}
    for feature in features:
        point_ids = [point["point_id"] for point in feature["points"]]
        for point_id in point_ids:
            adjacency.setdefault(point_id, set())
        for start, end in zip(point_ids, point_ids[1:]):
            if start == end:
                continue
            adjacency[start].add(end)
            adjacency[end].add(start)
    components = 0
    remaining = set(adjacency)
    while remaining:
        components += 1
        stack = [remaining.pop()]
        while stack:
            current = stack.pop()
            for neighbor in adjacency[current]:
                if neighbor in remaining:
                    remaining.remove(neighbor)
                    stack.append(neighbor)
    return components


def _prepare_corrections(
    corrections: Sequence[dict[str, Any]],
) -> tuple[set[str], dict[str, dict[str, Any]], list[dict[str, Any]]]:
    exclusions: set[str] = set()
    reclassifications: dict[str, dict[str, Any]] = {}
    additions: list[dict[str, Any]] = []
    for correction in corrections:
        if correction["review_status"] != "accepted":
            continue
        if correction["operation"] == "exclude":
            exclusions.add(correction["target_parent_feature_id"])
        elif correction["operation"] == "reclassify":
            reclassifications[correction["target_parent_feature_id"]] = correction
        elif correction["operation"] == "add":
            additions.append(correction)
    return exclusions, reclassifications, additions


def build_source_document(
    *,
    osm_document: dict[str, Any],
    bbox: BBox,
    overpass_url: str,
    query: str,
    input_mode: str,
    corrections_document: dict[str, Any],
    dataset_id: str = DATASET_ID,
) -> dict[str, Any]:
    osm_document = normalise_overpass_document(osm_document)
    corrections = validate_manual_corrections(corrections_document, dataset_id)
    exclusions, reclassifications, additions = _prepare_corrections(corrections)

    elements = osm_document["elements"]
    nodes: dict[int, SourcePoint] = {}
    ways: list[dict[str, Any]] = []
    for element in elements:
        if not isinstance(element, dict):
            continue
        element_type = element.get("type")
        if element_type == "node":
            try:
                node_id = int(element["id"])
                longitude = float(element["lon"])
                latitude = float(element["lat"])
            except (KeyError, TypeError, ValueError):
                continue
            nodes[node_id] = SourcePoint(
                point_id=f"osm-node-{node_id}",
                longitude=longitude,
                latitude=latitude,
                osm_node_id=node_id,
            )
        elif element_type == "way":
            ways.append(element)

    features: list[dict[str, Any]] = []
    decisions: Counter[str] = Counter()
    rejected_examples: list[dict[str, str]] = []
    accepted_parent_ids: set[str] = set()

    for way in sorted(ways, key=lambda item: int(item.get("id", 0))):
        try:
            way_id = int(way["id"])
        except (KeyError, TypeError, ValueError):
            decisions["reject-invalid-way-id"] += 1
            continue
        parent_feature_id = f"osm-way-{way_id}"
        tags = normalise_tags(way.get("tags"))
        admission = classify_way(tags)
        if parent_feature_id in exclusions:
            admission = Admission(False, None, "reject-manual-exclusion")
        elif parent_feature_id in reclassifications and admission.accepted:
            correction = reclassifications[parent_feature_id]
            admission = Admission(
                True,
                correction["classification"],
                "allow-manual-reclassification",
                requires_manual_review=False,
            )
        decisions[admission.rule] += 1
        if not admission.accepted or admission.classification is None:
            if len(rejected_examples) < 100:
                rejected_examples.append(
                    {"origin_id": parent_feature_id, "reason": admission.rule}
                )
            continue

        node_ids = way.get("nodes")
        if not isinstance(node_ids, list) or len(node_ids) < 2:
            decisions["reject-missing-way-geometry"] += 1
            if len(rejected_examples) < 100:
                rejected_examples.append(
                    {"origin_id": parent_feature_id, "reason": "reject-missing-way-geometry"}
                )
            continue
        try:
            points = [nodes[int(node_id)] for node_id in node_ids]
        except (KeyError, TypeError, ValueError):
            decisions["reject-missing-referenced-node"] += 1
            if len(rejected_examples) < 100:
                rejected_examples.append(
                    {"origin_id": parent_feature_id, "reason": "reject-missing-referenced-node"}
                )
            continue

        runs = split_polyline_into_cells(points, bbox, parent_feature_id)
        if not runs:
            decisions["reject-no-geometry-inside-bbox"] += 1
            continue
        accepted_parent_ids.add(parent_feature_id)
        origin = {
            "provider": "OpenStreetMap",
            "element_type": "way",
            "element_id": way_id,
            "version": int(way["version"]) if way.get("version") is not None else None,
        }
        for part_index, (feature_cell_id, run_points) in enumerate(runs):
            features.append(
                _feature_from_run(
                    parent_feature_id=parent_feature_id,
                    origin=origin,
                    classification=admission.classification,
                    admission_rule=admission.rule,
                    requires_manual_review=admission.requires_manual_review,
                    feature_cell_id=feature_cell_id,
                    part_index=part_index,
                    way_directionality=directionality(tags),
                    points=run_points,
                    tags=tags,
                )
            )

    for correction in additions:
        correction_id = correction["correction_id"]
        parent_feature_id = f"manual-{correction_id}"
        points = [
            SourcePoint(
                point_id=f"{parent_feature_id}-point-{index:03d}",
                longitude=float(coordinate[0]),
                latitude=float(coordinate[1]),
                osm_node_id=None,
            )
            for index, coordinate in enumerate(correction["points_wgs84"])
        ]
        runs = split_polyline_into_cells(points, bbox, parent_feature_id)
        if not runs:
            decisions["reject-manual-add-outside-bbox"] += 1
            continue
        accepted_parent_ids.add(parent_feature_id)
        for part_index, (feature_cell_id, run_points) in enumerate(runs):
            features.append(
                _feature_from_run(
                    parent_feature_id=parent_feature_id,
                    origin={
                        "provider": "manual-correction",
                        "element_type": "manual-polyline",
                        "element_id": correction_id,
                        "version": None,
                    },
                    classification=correction["classification"],
                    admission_rule="allow-accepted-manual-add",
                    requires_manual_review=False,
                    feature_cell_id=feature_cell_id,
                    part_index=part_index,
                    way_directionality="bidirectional",
                    points=run_points,
                    tags={},
                )
            )
        decisions["allow-accepted-manual-add"] += 1

    features.sort(key=lambda feature: feature["feature_id"])
    feature_ids_by_cell: dict[str, list[str]] = {
        cell_id(column, row): []
        for row in range(GRID_ROWS)
        for column in range(GRID_COLUMNS)
    }
    for feature in features:
        feature_ids_by_cell[feature["cell_id"]].append(feature["feature_id"])

    cells = []
    for row in range(GRID_ROWS):
        for column in range(GRID_COLUMNS):
            identifier = cell_id(column, row)
            cells.append(
                {
                    "cell_id": identifier,
                    "grid_coordinate": [column, row],
                    "bounds_wgs84": bbox.cell_bounds(column, row).as_dict(),
                    "source_feature_ids": sorted(feature_ids_by_cell[identifier]),
                }
            )

    classification_counts = Counter(
        feature["classification"] for feature in features
    )
    manual_review_feature_part_count = sum(
        1 for feature in features if feature["requires_manual_review"]
    )
    total_source_length_m = sum(
        geodesic_length_m(feature["points"]) for feature in features
    )
    connected_component_count = coarse_connected_component_count(features)
    correction_counts = Counter(
        f"{correction['review_status']}-{correction['operation']}"
        for correction in corrections
    )
    raw_way_count = sum(1 for element in elements if element.get("type") == "way")
    raw_node_count = sum(1 for element in elements if element.get("type") == "node")
    osm_base_timestamp = None
    if isinstance(osm_document.get("osm3s"), dict):
        value = osm_document["osm3s"].get("timestamp_osm_base")
        osm_base_timestamp = str(value) if value is not None else None

    document: dict[str, Any] = {
        "$schema": "../central_pedestrian_source.schema.json",
        "schema_version": SCHEMA_VERSION,
        "dataset_id": dataset_id,
        "build_id": HASH_PLACEHOLDER,
        "generator": {"name": GENERATOR_NAME, "version": GENERATOR_VERSION},
        "source": {
            "provider": "OpenStreetMap",
            "attribution": "© OpenStreetMap contributors",
            "license": "ODbL-1.0",
            "overpass_url": overpass_url,
            "query": query,
            "query_sha256": hashlib.sha256(query.encode("utf-8")).hexdigest(),
            "raw_sha256": sha256_value(osm_document),
            "input_mode": input_mode,
            "osm_base_timestamp": osm_base_timestamp,
        },
        "bounds_wgs84": bbox.as_dict(),
        "grid": {
            "columns": GRID_COLUMNS,
            "rows": GRID_ROWS,
            "cell_order": "south-to-north, west-to-east",
        },
        "cells": cells,
        "features": features,
        "manual_corrections": corrections,
        "audit": {
            "raw_element_count": len(elements),
            "raw_way_count": raw_way_count,
            "raw_node_count": raw_node_count,
            "accepted_parent_feature_count": len(accepted_parent_ids),
            "output_feature_part_count": len(features),
            "rejected_parent_feature_count": max(
                0, raw_way_count - len(accepted_parent_ids)
            ),
            "manual_review_feature_part_count": manual_review_feature_part_count,
            "total_source_length_m": round(total_source_length_m, 3),
            "coarse_connected_component_count": connected_component_count,
            "classification_counts": dict(sorted(classification_counts.items())),
            "cell_feature_counts": {
                identifier: len(feature_ids)
                for identifier, feature_ids in sorted(feature_ids_by_cell.items())
            },
            "decision_counts": dict(sorted(decisions.items())),
            "manual_correction_counts": dict(sorted(correction_counts.items())),
            "rejected_examples": sorted(
                rejected_examples, key=lambda example: example["origin_id"]
            ),
        },
        "hashes": {
            "algorithm": "SHA-256",
            "topology_sha256": HASH_PLACEHOLDER,
            "document_sha256": HASH_PLACEHOLDER,
        },
    }

    topology_payload = {
        "schema_version": document["schema_version"],
        "dataset_id": document["dataset_id"],
        "bounds_wgs84": document["bounds_wgs84"],
        "grid": document["grid"],
        "cells": document["cells"],
        "features": document["features"],
        "manual_corrections": document["manual_corrections"],
    }
    topology_sha256 = sha256_value(topology_payload)
    document["hashes"]["topology_sha256"] = topology_sha256
    document["build_id"] = str(
        uuid.uuid5(BUILD_NAMESPACE, f"{dataset_id}:{topology_sha256}")
    )
    document_for_hash = copy.deepcopy(document)
    document_for_hash["hashes"]["document_sha256"] = HASH_PLACEHOLDER
    document["hashes"]["document_sha256"] = sha256_value(document_for_hash)
    return document


def validate_schema(document: Any, schema_path: Path = SCHEMA_PATH) -> None:
    try:
        import jsonschema
    except ImportError as error:
        raise PipelineError(
            "jsonschema is required; install Scripts/OpenMassCrowd/"
            "CentralNetwork/requirements.txt"
        ) from error
    schema = load_json(schema_path)
    validator = jsonschema.Draft202012Validator(
        schema, format_checker=jsonschema.FormatChecker()
    )
    errors = sorted(validator.iter_errors(document), key=lambda item: list(item.path))
    if errors:
        messages = []
        for error in errors[:20]:
            location = ".".join(str(part) for part in error.absolute_path) or "$"
            messages.append(f"{location}: {error.message}")
        raise PipelineError("schema validation failed:\n  " + "\n  ".join(messages))


def validate_semantics(document: dict[str, Any]) -> None:
    bbox = BBox(**document["bounds_wgs84"])
    bbox.validate()
    expected_cells = [
        cell_id(column, row)
        for row in range(GRID_ROWS)
        for column in range(GRID_COLUMNS)
    ]
    actual_cells = [cell["cell_id"] for cell in document["cells"]]
    if actual_cells != expected_cells:
        raise PipelineError(
            f"cell order/ids are not deterministic: expected {expected_cells}, got {actual_cells}"
        )
    features = document["features"]
    feature_ids = [feature["feature_id"] for feature in features]
    if feature_ids != sorted(feature_ids) or len(feature_ids) != len(set(feature_ids)):
        raise PipelineError("feature ids must be unique and lexically sorted")
    features_by_cell: dict[str, list[str]] = {identifier: [] for identifier in expected_cells}
    for feature in features:
        identifier = feature["cell_id"]
        if identifier not in features_by_cell:
            raise PipelineError(f"feature references unknown cell {identifier}")
        point_documents = feature["points"]
        if feature["geometry_sha256"] != sha256_value(point_documents):
            raise PipelineError(f"geometry hash mismatch for {feature['feature_id']}")
        for point in point_documents:
            if not bbox.contains(point["longitude"], point["latitude"], epsilon=2e-8):
                raise PipelineError(
                    f"{feature['feature_id']} contains a point outside the core"
                )
        features_by_cell[identifier].append(feature["feature_id"])
    for cell in document["cells"]:
        expected = sorted(features_by_cell[cell["cell_id"]])
        if cell["source_feature_ids"] != expected:
            raise PipelineError(f"cell feature index mismatch for {cell['cell_id']}")

    topology_payload = {
        "schema_version": document["schema_version"],
        "dataset_id": document["dataset_id"],
        "bounds_wgs84": document["bounds_wgs84"],
        "grid": document["grid"],
        "cells": document["cells"],
        "features": document["features"],
        "manual_corrections": document["manual_corrections"],
    }
    topology_sha256 = sha256_value(topology_payload)
    if document["hashes"]["topology_sha256"] != topology_sha256:
        raise PipelineError("topology_sha256 does not match canonical topology")
    expected_build_id = str(
        uuid.uuid5(BUILD_NAMESPACE, f"{document['dataset_id']}:{topology_sha256}")
    )
    if document["build_id"] != expected_build_id:
        raise PipelineError("build_id is not the deterministic topology UUID")
    document_for_hash = copy.deepcopy(document)
    document_for_hash["hashes"]["document_sha256"] = HASH_PLACEHOLDER
    if document["hashes"]["document_sha256"] != sha256_value(document_for_hash):
        raise PipelineError("document_sha256 does not match canonical document")


def validate_source_document(document: dict[str, Any], schema_path: Path = SCHEMA_PATH) -> None:
    validate_schema(document, schema_path)
    validate_semantics(document)


def validate_projected_document(
    document: dict[str, Any], schema_path: Path = PROJECTED_SCHEMA_PATH
) -> None:
    validate_schema(document, schema_path)
    georeference = copy.deepcopy(document["georeference"])
    georeference_sha256 = georeference.pop("sha256")
    if georeference_sha256 != sha256_value(georeference):
        raise PipelineError("projected georeference hash mismatch")
    for feature in document["features"]:
        if feature["projected_geometry_sha256"] != sha256_value(feature["points"]):
            raise PipelineError(
                f"projected geometry hash mismatch for {feature['feature_id']}"
            )
    projected_geometry_sha256 = sha256_value(
        [
            {
                "feature_id": feature["feature_id"],
                "projected_geometry_sha256": feature["projected_geometry_sha256"],
            }
            for feature in document["features"]
        ]
    )
    hashes = document["hashes"]
    if hashes["projected_geometry_sha256"] != projected_geometry_sha256:
        raise PipelineError("projected aggregate geometry hash mismatch")
    if hashes["georeference_sha256"] != georeference_sha256:
        raise PipelineError("projected top-level georeference hash mismatch")
    expected_combined = sha256_value(
        {
            "topology_sha256": hashes["topology_sha256"],
            "georeference_sha256": hashes["georeference_sha256"],
            "projected_geometry_sha256": hashes["projected_geometry_sha256"],
        }
    )
    if hashes["combined_sha256"] != expected_combined:
        raise PipelineError("projected combined hash mismatch")
    for cell in document["cells"]:
        content = {
            "cell_id": cell["cell_id"],
            "source_feature_ids": cell["source_feature_ids"],
            "world_bounds_cm": cell["world_bounds_cm"],
        }
        if cell["hashes"]["cell_content_sha256"] != sha256_value(content):
            raise PipelineError(f"projected cell hash mismatch for {cell['cell_id']}")
    target_population = sum(
        district["target_population"] for district in document["spawn_districts"]
    )
    if target_population != 300:
        raise PipelineError(
            f"projected source districts must allocate 300 people, got {target_population}"
        )
    if any(district["enabled"] for district in document["spawn_districts"]):
        raise PipelineError(
            "uncertified source districts must remain disabled (fail closed)"
        )


def make_audit_mirror(document: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": document["schema_version"],
        "dataset_id": document["dataset_id"],
        "build_id": document["build_id"],
        "bounds_wgs84": document["bounds_wgs84"],
        "source": document["source"],
        "hashes": document["hashes"],
        "audit": document["audit"],
        "cells": [
            {
                "cell_id": cell["cell_id"],
                "grid_coordinate": cell["grid_coordinate"],
                "bounds_wgs84": cell["bounds_wgs84"],
                "source_feature_count": len(cell["source_feature_ids"]),
            }
            for cell in document["cells"]
        ],
    }


def load_osm_input(
    *,
    input_path: Path | None,
    fixture: bool,
    allow_fixture_fallback: bool,
    overpass_url: str,
    query: str,
    timeout_seconds: float,
) -> tuple[dict[str, Any], str]:
    if fixture:
        return load_json(DEFAULT_FIXTURE_PATH), "fixture"
    if input_path is not None:
        return load_json(input_path), "file"
    try:
        return fetch_overpass(overpass_url, query, timeout_seconds), "overpass"
    except PipelineError:
        if not allow_fixture_fallback:
            raise
        print(
            "WARNING: Overpass unavailable; building the validation fixture only. "
            "Do not promote fixture output as the Central source dataset.",
            file=sys.stderr,
        )
        return load_json(DEFAULT_FIXTURE_PATH), "fixture"


def command_build(args: argparse.Namespace) -> int:
    bbox = BBox.parse(args.bbox)
    query = make_overpass_query(bbox)
    osm_document, input_mode = load_osm_input(
        input_path=args.input_osm,
        fixture=args.fixture,
        allow_fixture_fallback=args.allow_fixture_fallback,
        overpass_url=args.overpass_url,
        query=query,
        timeout_seconds=args.timeout,
    )
    normalised_raw = normalise_overpass_document(osm_document)
    corrections_document = load_json(args.manual_corrections)
    source = build_source_document(
        osm_document=normalised_raw,
        bbox=bbox,
        overpass_url=args.overpass_url,
        query=query,
        input_mode=input_mode,
        corrections_document=corrections_document,
        dataset_id=args.dataset_id,
    )
    validate_source_document(source, args.schema)
    write_pretty_json(args.output, source)
    write_pretty_json(args.audit_output, make_audit_mirror(source))
    if args.raw_output is not None:
        write_pretty_json(args.raw_output, normalised_raw)
    print(
        json.dumps(
            {
                "status": "ok",
                "input_mode": input_mode,
                "dataset_id": source["dataset_id"],
                "build_id": source["build_id"],
                "topology_sha256": source["hashes"]["topology_sha256"],
                "accepted_parent_features": source["audit"][
                    "accepted_parent_feature_count"
                ],
                "output_feature_parts": source["audit"]["output_feature_part_count"],
                "cell_feature_counts": source["audit"]["cell_feature_counts"],
                "output": str(args.output.resolve()),
                "audit_output": str(args.audit_output.resolve()),
                "raw_output": str(args.raw_output.resolve())
                if args.raw_output is not None
                else None,
            },
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def command_validate(args: argparse.Namespace) -> int:
    document = load_json(args.input)
    validate_source_document(document, args.schema)
    print(
        json.dumps(
            {
                "status": "ok",
                "input": str(args.input.resolve()),
                "dataset_id": document["dataset_id"],
                "build_id": document["build_id"],
                "feature_parts": len(document["features"]),
                "topology_sha256": document["hashes"]["topology_sha256"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def command_validate_projected(args: argparse.Namespace) -> int:
    document = load_json(args.input)
    validate_projected_document(document, args.schema)
    print(
        json.dumps(
            {
                "status": "ok",
                "input": str(args.input.resolve()),
                "network_id": document["network_id"],
                "build_id": document["build_id"],
                "feature_count": len(document["features"]),
                "point_count": document["evidence"]["candidate_point_count"],
                "georeference_sha256": document["hashes"]["georeference_sha256"],
                "projected_geometry_sha256": document["hashes"][
                    "projected_geometry_sha256"
                ],
                "combined_sha256": document["hashes"]["combined_sha256"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def command_self_test(args: argparse.Namespace) -> int:
    bbox = BBox.parse(DEFAULT_BBOX_TEXT)
    query = make_overpass_query(bbox)
    fixture = load_json(DEFAULT_FIXTURE_PATH)
    corrections = load_json(DEFAULT_CORRECTIONS_PATH)
    first = build_source_document(
        osm_document=fixture,
        bbox=bbox,
        overpass_url=DEFAULT_OVERPASS_URL,
        query=query,
        input_mode="fixture",
        corrections_document=corrections,
    )
    second = build_source_document(
        osm_document=copy.deepcopy(fixture),
        bbox=bbox,
        overpass_url=DEFAULT_OVERPASS_URL,
        query=query,
        input_mode="fixture",
        corrections_document=copy.deepcopy(corrections),
    )
    validate_source_document(first, args.schema)
    validate_source_document(second, args.schema)
    if canonical_json_bytes(first) != canonical_json_bytes(second):
        raise PipelineError("fixture conversion is not byte deterministic")
    if len(first["cells"]) != 6:
        raise PipelineError("fixture did not produce six cells")
    if not first["features"]:
        raise PipelineError("fixture did not produce accepted features")
    print(
        json.dumps(
            {
                "status": "ok",
                "deterministic": True,
                "fixture": str(DEFAULT_FIXTURE_PATH),
                "build_id": first["build_id"],
                "feature_parts": len(first["features"]),
                "decision_counts": first["audit"]["decision_counts"],
                "cell_feature_counts": first["audit"]["cell_feature_counts"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    build = subparsers.add_parser(
        "build", help="fetch/read OSM and build the deterministic source topology"
    )
    build.add_argument("--bbox", default=DEFAULT_BBOX_TEXT)
    build.add_argument("--dataset-id", default=DATASET_ID)
    build.add_argument("--overpass-url", default=DEFAULT_OVERPASS_URL)
    build.add_argument("--timeout", type=float, default=120.0)
    build.add_argument("--input-osm", type=Path)
    build.add_argument(
        "--fixture",
        action="store_true",
        help="use the small checked-in fixture instead of the network",
    )
    build.add_argument(
        "--allow-fixture-fallback",
        action="store_true",
        help="fall back to the fixture after a network error (never for promotion)",
    )
    build.add_argument(
        "--manual-corrections", type=Path, default=DEFAULT_CORRECTIONS_PATH
    )
    build.add_argument("--schema", type=Path, default=SCHEMA_PATH)
    build.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    build.add_argument("--raw-output", type=Path, default=DEFAULT_RAW_OUTPUT_PATH)
    build.add_argument(
        "--audit-output", type=Path, default=DEFAULT_AUDIT_OUTPUT_PATH
    )
    build.set_defaults(handler=command_build)

    validate = subparsers.add_parser(
        "validate", help="validate schema, indexes, stable hashes, and deterministic ID"
    )
    validate.add_argument("input", type=Path)
    validate.add_argument("--schema", type=Path, default=SCHEMA_PATH)
    validate.set_defaults(handler=command_validate)

    validate_projected = subparsers.add_parser(
        "validate-projected",
        help="validate the fail-closed Cesium-projected UE source mirror",
    )
    validate_projected.add_argument("input", type=Path)
    validate_projected.add_argument(
        "--schema", type=Path, default=PROJECTED_SCHEMA_PATH
    )
    validate_projected.set_defaults(handler=command_validate_projected)

    self_test = subparsers.add_parser(
        "self-test", help="validate the offline fixture twice and compare canonical bytes"
    )
    self_test.add_argument("--schema", type=Path, default=SCHEMA_PATH)
    self_test.set_defaults(handler=command_self_test)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.handler(args))
    except PipelineError as error:
        print(f"CENTRAL_OSM_PIPELINE_ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
